const FACEBOOK_GRAPH_API_BASE_URL = 'https://graph.facebook.com/v2.6/';
const PAGE_ACCESS_TOKEN = process.env.PAGE_ACCESS_TOKEN;

const request = require('request');

// postbacks
const GET_STARTED = 'GET_STARTED';
const REGISTRATION = 'REGISTRATION';
const CONTACT_US = 'CONTACT_US';
const BACK = 'BACK';

const CREATE_MEETING = 'CREATE_MEETING';
const ADDING_ORGANIZATOR = 'ADDING_ORGANIZATOR';

// db_requests
const INSERT_USER = "INSERT_USER";
const STARTED_REGISTRATION = "STARTED_REGISTRATION";
const GET_STATUS = "GET_STATUS";
const UPDATE_STATUS = "UPDATE_STATUS";
const UPDATE_NICKNAME = "UPDATE_NICKNAME";
const CONTACT_US_REDIRECT = "CONTACT_US_REDIRECT";
const GET_ALL_LANGUAGES = "GET_ALL_LANGUAGES";
const GET_USER_LANGUAGES = "GET_USER_LANGUAGES";
const DELETE_USER_LANGUAGES = "DELETE_USER_LANGUAGES";
const INSERT_USER_LANGUAGES = "INSERT_USER_LANGUAGES";
const GET_PERMISSION_LEVEL = "GET_PERMISSION_LEVEL";
const UPDATE_PERMISSION_LEVEL = "UPDATE_PERMISSION_LEVEL";
const GET_USERS_LIST_DATA = "GET_USERS_LIST_DATA";
const GET_ALL_PLACES = "GET_ALL_PLACES";
const INSERT_PLACE = "INSERT_PLACE";
const INSERT_MEETING = "INSERT_MEETING";
const GET_MEETINGS_LIST = "GET_MEETINGS_LIST";
const UPDATE_MEETING = "UPDATE_MEETING";
const GET_CURRENT_MEETING = "GET_CURRENT_MEETING";
const GET_USERS_ON_MEETING = "GET_USERS_ON_MEETING";
const UPDATE_VISITOR = "UPDATE_VISITOR";
const FINISH_MEETING = "FINISH_MEETING";
const GET_FUTURE_MEETINGS = "GET_FUTURE_MEETINGS";
const DELETE_VISITOR = "DELETE_VISITOR";
const INSERT_VISITOR = "INSERT_VISITOR";
const GET_HISTORY_MEETINGS = "GET_HISTORY_MEETINGS";

// statuses
const GOT_STARTED = "GOT_STARTED";
const CONTACTING_US = "CONTACTING_US";

// POSTGRESQL QUERIES
const GET_USER_DATA = 'SELECT * FROM users WHERE "facebookID"=$1::varchar';
const INSERT_USER_QUERY = 'INSERT INTO users("facebookID", status, nickname, "permissionLevel") VALUES($1::varchar, $2::varchar, NULL, \'0\')';
const UPDATE_CYCLE_STATUS = 'UPDATE users SET status=$1::varchar WHERE "facebookID"=$2::varchar';
const GET_STATUS_QUERY = 'SELECT status FROM users WHERE "facebookID"=$1::varchar';
const GET_PERMISSION_LEVEL_QUERY = 'SELECT "permissionLevel" FROM users WHERE "facebookID"=$1::varchar';
const UPDATE_PERMISSION_LEVEL_QUERY = 'UPDATE users SET "permissionLevel"=$1 WHERE "facebookID"=$2::varchar';
const UPDATE_NICKNAME_QUERY = 'UPDATE users SET nickname=$1::varchar WHERE "facebookID"=$2::varchar';
const GET_ALL_LANGUAGES_QUERY = 'SELECT getLanguagesArray()';
const GET_USER_LANGUAGES_QUERY = 'SELECT "langName" from languages WHERE "userID"=$1::varchar';
const DELETE_ALL_USER_LANGUAGES = 'DELETE FROM languages WHERE "userID"=$1::varchar';
const INSERT_USER_LANGUAGES_QUERY = 'INSERT INTO languages("userID", "langName") VALUES %L';
const GET_ALL_USERS_QUERY = 'SELECT "facebookID", "permissionLevel", nickname FROM users';
const GET_ALL_PLACES_QUERY = 'SELECT id, name, city, adress FROM places';
const INSERT_PLACE_QUERY = 'INSERT INTO places VALUES(DEFAULT, $1::varchar, $2::varchar, $3::varchar, $4::varchar, $5::varchar) RETURNING id, name, city, adress';
const INSERT_MEETING_QUERY = 'INSERT INTO meetings VALUES(DEFAULT, $1::int, $2::varchar, $3::varchar, $4::timestamptz, $5::timestamptz)';
const GET_MEETINGS_LIST_QUERY = 'SELECT * FROM getMeetingsList($1::varchar)';
const UPDATE_MEETING_QUERY = 'UPDATE meetings SET description=$1::varchar, "startDate"=$2::timestamptz, "endDate"=$3::timestamptz WHERE id=$4::int';
const GET_CURRENT_MEETING_QUERY = 'SELECT * FROM getAdministratedMeeting($1::varchar)';
const GET_USERS_ON_MEETING_QUERY = 'SELECT "userID", "isPresent", nickname FROM "meetingVisitors" m LEFT JOIN users u ON m."userID"=u."facebookID" WHERE "meetingID"=$1::int';
const UPDATE_VISITOR_QUERY = 'UPDATE "meetingVisitors" SET "isPresent"=$1::boolean WHERE "userID"=$2::varchar AND "meetingID"=$3::int';
const FINISH_MEETING_QUERY = 'UPDATE meetings SET "endDate"=NOW()::timestamptz WHERE id=$1::int';
const GET_FUTURE_MEETINGS_QUERY = 'SELECT * FROM getFutureMeetingsList($1::varchar)';
const INSERT_VISITOR_QUERY = 'INSERT INTO "meetingVisitors" VALUES($1::varchar, $2::int, false)';
const DELETE_VISITOR_QUERY = 'DELETE FROM "meetingVisitors" WHERE "userID"=$1::varchar AND "meetingID"=$2::int';
const GET_HISTORY_MEETINGS_QUERY = 'SELECT * FROM getHistoryMeetingsList($1::varchar)';


module.exports = {
    request: request,
    FACEBOOK_GRAPH_API_BASE_URL: FACEBOOK_GRAPH_API_BASE_URL,
    PAGE_ACCESS_TOKEN: PAGE_ACCESS_TOKEN,

    GET_STARTED: GET_STARTED,
    GOT_STARTED: GOT_STARTED,
    REGISTRATION: REGISTRATION,
    CONTACT_US: CONTACT_US,
    BACK: BACK,
  
    CREATE_MEETING: CREATE_MEETING,
    ADDING_ORGANIZATOR: ADDING_ORGANIZATOR,
   

    INSERT_USER: INSERT_USER,
    STARTED_REGISTRATION: STARTED_REGISTRATION,
    GET_STATUS: GET_STATUS,
    UPDATE_STATUS: UPDATE_STATUS,
    UPDATE_NICKNAME: UPDATE_NICKNAME,
    CONTACT_US_REDIRECT: CONTACT_US_REDIRECT,
    GET_ALL_LANGUAGES: GET_ALL_LANGUAGES,
    GET_USER_LANGUAGES: GET_USER_LANGUAGES,
    DELETE_USER_LANGUAGES: DELETE_USER_LANGUAGES,
    INSERT_USER_LANGUAGES: INSERT_USER_LANGUAGES,
    GET_PERMISSION_LEVEL: GET_PERMISSION_LEVEL,
    UPDATE_PERMISSION_LEVEL: UPDATE_PERMISSION_LEVEL,
    GET_USERS_LIST_DATA: GET_USERS_LIST_DATA,
    GET_ALL_PLACES, GET_ALL_PLACES,
    INSERT_PLACE: INSERT_PLACE,
    INSERT_MEETING: INSERT_MEETING,
    GET_MEETINGS_LIST: GET_MEETINGS_LIST,
    UPDATE_MEETING: UPDATE_MEETING,
    GET_CURRENT_MEETING: GET_CURRENT_MEETING,
    GET_USERS_ON_MEETING: GET_USERS_ON_MEETING,
    UPDATE_VISITOR: UPDATE_VISITOR,
    FINISH_MEETING: FINISH_MEETING,
    GET_FUTURE_MEETINGS: GET_FUTURE_MEETINGS,
    INSERT_VISITOR: INSERT_VISITOR,
    DELETE_VISITOR: DELETE_VISITOR,
    GET_HISTORY_MEETINGS: GET_HISTORY_MEETINGS,

    CONTACTING_US: CONTACTING_US,

    GET_USER_DATA: GET_USER_DATA,
    INSERT_USER_QUERY: INSERT_USER_QUERY,
    UPDATE_CYCLE_STATUS: UPDATE_CYCLE_STATUS,
    GET_STATUS_QUERY: GET_STATUS_QUERY,
    UPDATE_NICKNAME_QUERY: UPDATE_NICKNAME_QUERY,
    GET_ALL_LANGUAGES_QUERY: GET_ALL_LANGUAGES_QUERY,
    GET_USER_LANGUAGES_QUERY: GET_USER_LANGUAGES_QUERY,
    DELETE_ALL_USER_LANGUAGES: DELETE_ALL_USER_LANGUAGES,
    INSERT_USER_LANGUAGES_QUERY: INSERT_USER_LANGUAGES_QUERY,
    GET_PERMISSION_LEVEL_QUERY: GET_PERMISSION_LEVEL_QUERY,
    UPDATE_PERMISSION_LEVEL_QUERY: UPDATE_PERMISSION_LEVEL_QUERY,
    GET_ALL_USERS_QUERY: GET_ALL_USERS_QUERY,
    GET_ALL_PLACES_QUERY: GET_ALL_PLACES_QUERY,
    INSERT_PLACE_QUERY: INSERT_PLACE_QUERY,
    INSERT_MEETING_QUERY: INSERT_MEETING_QUERY,
    GET_MEETINGS_LIST_QUERY: GET_MEETINGS_LIST_QUERY,
    UPDATE_MEETING_QUERY: UPDATE_MEETING_QUERY,
    GET_CURRENT_MEETING_QUERY: GET_CURRENT_MEETING_QUERY,
    GET_USERS_ON_MEETING_QUERY: GET_USERS_ON_MEETING_QUERY,
    UPDATE_VISITOR_QUERY: UPDATE_VISITOR_QUERY,
    FINISH_MEETING_QUERY: FINISH_MEETING_QUERY,
    GET_FUTURE_MEETINGS_QUERY: GET_FUTURE_MEETINGS_QUERY,
    INSERT_VISITOR_QUERY: INSERT_VISITOR_QUERY,
    DELETE_VISITOR_QUERY: DELETE_VISITOR_QUERY,
    GET_HISTORY_MEETINGS_QUERY: GET_HISTORY_MEETINGS_QUERY,
}