const FACEBOOK_GRAPH_API_BASE_URL = 'https://graph.facebook.com/v2.6/';
const PAGE_ACCESS_TOKEN = process.env.PAGE_ACCESS_TOKEN;

const request = require('request');

// postbacks
const GREETING = 'GREETING';
const START_REGISTRATION_YES = 'START_REGISTRATION_YES';
const START_REGISTRATION_NO = 'START_REGISTRATION_NO';
const CANCEL = 'CANCEL';

module.exports = {
    request: request,
    FACEBOOK_GRAPH_API_BASE_URL: FACEBOOK_GRAPH_API_BASE_URL,
    PAGE_ACCESS_TOKEN: PAGE_ACCESS_TOKEN,
    GREETING: GREETING,
    START_REGISTRATION_YES: START_REGISTRATION_YES,
    START_REGISTRATION_NO: START_REGISTRATION_NO,
    CANCEL: CANCEL,
}