DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS language CASCADE;
DROP TABLE IF EXISTS organizators CASCADE;
DROP TABLE IF EXISTS "meetingVisitors" CASCADE;
DROP TABLE IF EXISTS meetings CASCADE;
DROP TABLE IF EXISTS places CASCADE;
DROP TABLE IF EXISTS users CASCADE;
